image: python:3.6

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

static:
  stage: test
  before_script:
    - pip install semgrep
  script:
    - semgrep --error --config=p/r2c-ci .
  only:
    changes:
      - "**/*.py"
  except:
    - tags

lint:
  stage: test
  before_script:
    - pip install -r requirements-dev.txt
  script:
    - pylint **/*.py
  only:
    changes:
      - "**/*.py"
  except:
    - tags

unit:
  stage: test
  before_script:
    - pip install -r requirements.txt
  script:
    - ./run_tests.sh
  except:
    - tags
